spring.application.name=messaging-app
server.port=8080

# MongoDB Configuration
# IMPORTANT: Replace <db_password> with your actual MongoDB password before running!
spring.data.mongodb.uri=mongodb+srv://RavPd:RavPd%40%40%23%5E%26@cluster0.0dl4mgm.mongodb.net/nexuschat?appName=Cluster0

# WebSockets Configuration
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
